# .github/workflows/cd.yml
name: CD

on:
  workflow_run:
    workflows: ["CI"]      # the name of your CI workflow
    types: [completed]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: 22
          script: |
            cd /home/${{ secrets.DEPLOY_USER }} || exit 1
            
            mkdir -p ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts

            if [ ! -d "express-basics" ]; then
                git clone git@github.com:4lrozi/express-basics.git
            fi

            cd express-basics
            git fetch --all
            git reset --hard origin/main

            # Write .env file from secret
            echo "${{ secrets.ENV_FILE_BASE64 }}" | base64 -d > .env

            docker-compose pull
            docker-compose up -d --build
            docker-compose run --rm api npm run migrate
            docker-compose run --rm api npm run seed
